### ISSUE TITLE
Not yet reflected about bandwidth charges for copying objects

### ISSUE THREAD

**Issue by khayama** [ibm-cloud-docs/cloud-object-storage#100]
@nglange  Please follow and reflect it, thanks.

bandwidth charges for copying objects by khayama · Pull Request #69 · ibm-cloud-docs/cloud-object-storage : https://github.com/ibm-cloud-docs/cloud-object-storage/pull/69

**Comment by cloudpitchford** [comment]
@khayama can you confirm this change has been published and close this issue? Thanks!

**Comment by khayama** [comment]
I have confirmed it's been published, thanks!
