### ISSUE TITLE
creating bucket fails with "Invalid argument"

### ISSUE THREAD

**Issue by spackows** [ibm-cloud-docs/cloud-object-storage#101]
**Description**
I am trying to create a bucket in COS using a Node.js app, following this example:
[https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-node#node-examples-new-bucket](https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-node#node-examples-new-bucket)

But I keep getting the error: `Invalid Argument`

I tried a few different options for LocationConstraint here: https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-classes#classes

**To Reproduce**
Sample code is attached: [test.js.txt](https://github.com/ibm-cloud-docs/cloud-object-storage/files/4800068/test.js.txt)

**Desktop (please complete the following information):**
Running on Windows 10.

**Additional context**
Note that I am using the CIO Public Cloud account, and I know that account keeps running out of IAM credentials:
![image](https://user-images.githubusercontent.com/18294329/85051402-7589cd80-b165-11ea-9620-afbcb41e4e2d.png)

So many the problem is that this failure is being caught poorly and the wrong error message is being returned??

**Comment by cloudpitchford** [comment]
I appreciate the details, @spackows and I've begun to troubleshoot the issue. I'll try to reproduce the error that you received. When I tried to create the bucket you had already created, I got a standard error message as should be expected. When I create a new bucket, I get a standard success message as expected.

I also appreciate any suggestions to improve the sample code:

```
var config = {
    endpoint: 's3.us-south.cloud-object-storage.appdomain.cloud',
    apiKeyId: '9-...--...-s',
    ibmAuthEndpoint: 'https://iam.cloud.ibm.com/identity/token',
    serviceInstanceId: 'crn:v1:bluemix:public:cloud-object-storage:global:a/8-.-5:4-f-2-nnnn-nnnn-nnnnnnnnnnn::',
};

var cosClient = new myCOS.S3(config);
const channel_id = "my-test-1592497075613";

function createBucket(bucketName) {
    console.log(`Creating new bucket: ${bucketName}`);
    return cosClient.createBucket({
        Bucket: bucketName,
        CreateBucketConfiguration: {
            LocationConstraint: 'us-south-standard'
        },
    }).promise()
        .then((() => {
            console.log(`Bucket: ${bucketName} created!`);
        }))
        .catch((e) => {
            console.error(`ERROR: ${e.code} - ${e.message}\n`);
        });
}
```

And I'll track down where the particular message is coming from and ask an SDK engineer to look into the specifics from that side of the problem. Thanks again, and I'll look for any updates from you in the meantime.

**Comment by cloudpitchford** [comment]
I haven't encountered the "Invalid Argument" yet as I've been breaking my credentials or location constraints and received expected errors:

`ERROR: InvalidLocationConstraint - Invalid provisioning code.  Container storage location not available` and `ERROR: CredentialsError - Missing credentials in config` but I will bring this up with the SDK engineers in this morning's status meeting.

**Comment by spackows** [comment]
### [Update]

The CIO team cleaned up IAM policies:
- Now, when I create buckets manually, I don't see the out-of-policies error [1]
- And the sample code attached to this defect runs successfully

[1] When my code wasn't running the other day, I was creating buckets manually.  When I was creating buckets manually, I would see the out-of-IAM-policies error, but the buckets got created.



Ideally, that out-of-policies error should be handled more gracefully in `ibm-cos-sdk` : 
- At least a better error message - the args weren't invalid
- The code should create the bucket and return a warning that no new credentials were created for the bucket
- Maybe automatically creating new credentials for every new bucket isn't such a great idea??

Then again, running out of IAM policies seems like a pretty unusual problem.  The limit is ~100000.  Probably no company other than IBM tries to make thousands of employees all use the same IBM Cloud account.  🤣 

Anyway, I'm going to close this because improving error handling for an edge case is always too low priority to ever actually get done.  At least the issue is documented here.
