### ISSUE TITLE
"Request an IAM token by using an API key section" in curl tutorial can be confusing

### ISSUE THREAD

**Issue by saulotdr** [ibm-cloud-docs/cloud-object-storage#102]
Hi, how are you?

I noticed the [api_key has the value between braces](https://cloud.ibm.com/docs/cloud-object-storage/cli?topic=cloud-object-storage-curl#curl-token) and the expected is to have the API Key written without them. 

I think It would be nice to have a warn to remove the braces before proceeding with the request.

Thanks and regards,
Saulo

**Comment by nglange** [comment]
Thanks Saulo - that's a great suggestion. When the change is made I'll update and close this ticket.

**Comment by cloudpitchford** [comment]
This has been addressed with the latest release to production and can be closed.
