### ISSUE TITLE
COS_SERVICE_CRN missing & superfluos COS_AUTH_ENDPOINT

### ISSUE THREAD

**Issue by guglielmosanchini** [ibm-cloud-docs/cloud-object-storage#103]
1) Code Examples, Initializing configuration:
 in the client object code snippet, COS_SERVICE_CRN should be instantiated but is missing

2) Large Object Upload by using TransferManager:
in the upload_large_file function, the line 
```
ibm_auth_endpoint=COS_AUTH_ENDPOINT,
```
is superfluous and/or wrong, I did not test it with sufficient care.

**Comment by cloudpitchford** [comment]
Thanks for the comment, and it looks like you're trying to use one of the SDKs (possibly Python).

There are different code patterns available to the SKDs to create a connection, using clients and resources as different methodologies for example. Can you provide any more information regarding the specifics of what you were trying to attempt? Thanks again.

**Comment by cloudpitchford** [comment]
With more than one month since the last activity it seems this issue has been addressed, and otherwise should be closed? Thanks!
