### ISSUE TITLE
When migrating to ICOS it should be noted that there is no outbound BW charges on PRIVATE network

### ISSUE THREAD

**Issue by jdIBM** [ibm-cloud-docs/cloud-object-storage#104]
When migrating to ICOS it should be noted that there is no outbound BW charges on PRIVATE network, and to clarify that in the docs to prevent mis-configuration

**Comment by cloudpitchford** [comment]
One month since the last activity suggests that this issue might have been addressed or should otherwise be closed. Thanks!

**Comment by cloudpitchford** [comment]
I'll close this issue, but please feel free to open a new one to continue the discussion.
