### ISSUE TITLE
Using Minio Client Documentation

### ISSUE THREAD

**Issue by Shrinidhikulkarni7** [ibm-cloud-docs/cloud-object-storage#106]
The syntax says -
mc config host add <ALIAS> <COS-ENDPOINT> <ACCESS-KEY> <SECRET-KEY>

When I read about it in the document, the access key and secret key, the definitions for both are -,

<ACCESS-KEY> - access key that is assigned to your Service Credential

<SECRET-KEY> - secret key that is assigned to your Service Credential

But in my service credentials, the field I get are
"apikey"
 "endpoints"
 "iam_apikey_description"
 "iam_apikey_name"
 "iam_role_crn"
 "iam_serviceid_crn"
 "resource_instance_id"

Is it possible to add where I could fetch those?

**Comment by nglange** [comment]
Here's the topic for getting HMAC keys in a service credential: https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-uhc-hmac-credentials-main

Would be good to have a standing link to that topic at the top of any S3-compatible tool though.
