### ISSUE TITLE
routing needs a better description for global redirect

### ISSUE THREAD

**Issue by powellquiring** [ibm-cloud-docs/cloud-object-storage#107]
![image](https://user-images.githubusercontent.com/6932057/97345283-193b6680-1847-11eb-8f30-55b450afe25e.png)

https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-static-website-options#static-websites-options-adv-conf

**Currently**:

Routing
Routing gives you control over the requests coming from your visitors. For example, you could globally redirect all of your traffic from using one protocol to another, like replacing HTTP with the secure HTTPS. Or, you can create individual rules that process incoming requests for specific files and provide responses to your visitors based on the rules you define.

**Suggest global be pulled into it's own paragraph**:

The Redirect all requests (global) puts the bucket in a mode where it does not return contents from the bucket.  All urls to this bucket will be redirected to the hostname provided.  The http response will be a Status Code 301 and a redirect with the same path.

For example after the bucket is created a public URL might be: http://myuniquebucketname.s3-web.us-south.cloud-object-storage.appdomain.cloud. If the hostname was mywebsite.mydomain.com then an attempt to access http://myuniquebucketname.s3-web.us-south.cloud-object-storage.appdomain.cloud/path/file.html would result in a http redirect to http://mywebsite.mydomain.com/path/file.html.  If https was selected instead of http then the redirect would be https://...

More info:

Slack https://ibm-cloudplatform.slack.com/archives/CTXUNUXV1/p1603822557297500

So If I wanted all users attempting to access this bucket to instead go to say ibm.com, I would setup Redirectallrequests to ibm.com

**Comment by cloudpitchford** [comment]
Thanks for the feedback! An internal ticket has been opened to track, so I'm gratefully closing this issue.

**Comment by powellquiring** [comment]
can you provide a url to the ticket?

**Comment by cloudpitchford** [comment]
Of course. Please Slack me, as it's internal only and this is a public repo.
