### ISSUE TITLE
SSE-KP - No need to keep Key Protect key backups anymore

### ISSUE THREAD

**Issue by BrunoHenriques** [ibm-cloud-docs/cloud-object-storage#109]
The following section of https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-kp#kp-lifecycle
can be deleted.

"If a key that was originally uploaded by a user is deleted, and then restored using different key material, it will result in a loss of data. It is recommended to keep n-5 keys archived somewhere in order to ensure that the correct key material is available for restoration."

Key Protect v2.73 is in production. It is now possible to restore any key, standard or root, imported or not, using the Key Protect API and there is no need to back up Key material.

**Comment by nglange** [comment]
Thanks Bruno - this will be removed in the release later this week.

**Comment by cloudpitchford** [comment]
Closed as addressed and released.
