### ISSUE TITLE
Add an indication on the Access Key and Secret Key

### ISSUE THREAD

**Issue by airvb** [ibm-cloud-docs/cloud-object-storage#111]
**Is your feature request related to a problem? Please describe.**
Very difficult to make relation between cos_hmac_keys and access key and secret key 

**Describe the solution you'd like**
In chapter 6 , added information where to find access key and secret key 
link forward 
[(https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-service-credentials)]

**Describe alternatives you've considered**
Explanation to cos_hmac_keys

**Comment by WP-LKL** [comment]
The following discussion encapsulates the confusion - which are two-fold.

1. The requirement to enable hmac in advanced when registering new credentials. 

2. How one should pick the server in the Rclone config.

I suggest providing an example config for further clarification.

**Comment by WP-LKL** [comment]
Here is an example, the endpoint can be found under "view configuration".
rclone.conf:
```
[IBM]
type = s3
provider = IBMCOS
env_auth = false
access_key_id = <hmac-credential-access_key_id>
secret_access_key = <hmac-credential-secret_access_key>
endpoint = s3.private.eu-de.cloud-object-storage.appdomain.cloud
location_constraint = eu-standard
acl = private
```

**Comment by airvb** [comment]
Hello, thanks for your reply.
I was my contribution on Rclone forum,

I suggest to put the link to the creation of identification data.
https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-service-credentials&locale=en

-Indicate that the HMAC credentials must be generated,

-Indicate that 'cos_hmac_keys' are the data to be used for 
access_key_id and secret_access_key.

For endpoints, it should also be clarified how to choose the right one in the list, because when the key is created, the address 'https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints' appears.
Moreover, when you don't choose the right one, rclone isn't very explicit about the error.
example :
With this bad configuration, I chose
Cross Region Endpoints / EU Cross Region /public 
```
[ibm]
type = s3
provider = IBMCOS
env_auth = false
access_key_id = SECRET
secret_access_key = SECRET
endpoint = s3.eu-de.cloud-object-storage.appdomain.cloud
location_constraint = 
acl = private
```
Trying to connect :
rclone lsd ibm:airvb-1 -vv
2021/01/28 09:41:49 DEBUG : rclone: Version "v1.53.4" starting with parameters ["rclone" "lsd" "ibm:airvb-1" "-vv"]
2021/01/28 09:41:49 DEBUG : Using config file from "/home/airvb/.config/rclone/rclone.conf"
2021/01/28 09:41:49 DEBUG : Creating backend with remote "ibm:airvb-1"
2021/01/28 09:41:50 ERROR : : error listing: directory not found
2021/01/28 09:41:50 DEBUG : 4 go routines active
2021/01/28 09:41:50 Failed to lsd with 2 errors: last error was: directory not found

This gives little indication of the error, and certainly not an indication of the wrong choice of endpoints :(

But it's just my opinion
