### ISSUE TITLE
Cloud Object Storage

### ISSUE THREAD

**Issue by rgentyala** [ibm-cloud-docs/cloud-object-storage#116]
Catalog --> Services --> Object Storage .. has these below 2 topics "Docs and API Docs". Docs link is pointing to first https link given below that doesn't work and second link works. We need to fix the first link of Docs and may be that need to point to second link. If you have any questions let me know.

https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-getting-started

https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-getting-started-cloud-object-storage

**Comment by nglange** [comment]
Clearing out old issues - this has been fixed.
