### ISSUE TITLE
Unable to upload form data to cos

### ISSUE THREAD

**Issue by vishalisudharson** [ibm-cloud-docs/cloud-object-storage#122]
while passing form data as input to upload method receiving following error,

Errror:
The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. 
Received undefined.

Code:
const objectStore = require('ibm-cos-sdk');
var con = {
  endpoint: ***,
  apiKeyId: ***,
  region: ***,
  serviceInstanceId: ***,
 };

 var cos = new objectStore.S3(con);

var upload = multer({
  storage: multerS3({
    s3: cos,
    bucket: '***',
    contentType: multerS3.AUTO_CONTENT_TYPE,
    metadata: function (req, file, cb) {
      console.log(file.fieldname,file.originalname);
      cb(null, {fieldName: file.fieldname});
    },
    key: 
    function (req, file, cb) {
      console.log(file.originalname);
      console.log(file);
      cb(null, Date.now().toString()+ "_" + file.originalname);
    }

**Comment by nglange** [comment]
Can you edit this to remove the API key (and please destroy the compromised API key), and then reformat to use a code block?  The lack of formatting makes this difficult to troubleshoot.  Thanks!

**Comment by vishalisudharson** [comment]
I have destroyed the key values. Is there any way on uploading formdata to cos.
