### ISSUE TITLE
Stuck in Japanese language

### ISSUE THREAD

**Issue by crdotson** [ibm-cloud-docs/cloud-object-storage#123]
This is probably not specific to Cloud Object Storage documentation.  

I followed a link from google to http://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-at-events&locale=jp and my language for cloud.ibm.com/docs got stuck in Japanese.  I modified the URL manually to http://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-at-events&locale=us to try to see the page in Engish and the main text showed in English but the sidebar/etc. still showed as Japanese.  Going to https://cloud.ibm.com/docs directly after that showed in Japanese.  I had to clear domain cookies using the Firefox Web Developer extension to fix. 

Using Firefox 89.0.2 (64-bit)

**Comment by nglange** [comment]
Ahhhh - thanks for raising this, even if it's probably an issue with the framework itself.  I'll find the right place to file the issue, and will update you here.

**Comment by jenschlot** [comment]
@crdotson what was the phrase you searched on in Google? We’ll look into why it’s returning a result with a language locale on the url. 

In the meantime, use the language switcher in the footer of the content page to reset the app to English.

**Comment by willholley** [comment]
I've been experiencing this for the couple of weeks as well. The target language doens't appear to be consistent - perhaps it's just the last langugage indexed by Google?

For example, I searched Google for `cloudant replication iam` and the top match `Cloudant - Replication - IBM Cloud` links to https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-replication-api&locale=ko

**Comment by crdotson** [comment]
I just had it happen again -- in my case I searched for:

site:cloud.ibm.com 2fa

and it went to https://cloud.ibm.com/docs/activity-tracker?topic=activity-tracker-bss_mfa_events&locale=ko .  After that, going manually to https://cloud.ibm.com/docs still shows in Korean.  It's not clear how to change the language back unless you know Korean.
