### ISSUE TITLE
Connecting to Private Endpoint from VPC

### ISSUE THREAD

**Issue by PKehnel** [ibm-cloud-docs/cloud-object-storage#153]
- [x] In the VPC environment we are supposed to use direct endpoints

For a test I'm trying to reach a COS private endpoint from a VSI in a VPC. 
Is this supposed to work in theory? 

I'm using rclone. 
The code snippet below works fine if I use the `direct endpoint` but fails with the private endpoint. 

Just want to understand if this is intended or if the mistake is something else.

```
[COS_SOURCE]
type = s3
provider = IBMCOS
env_auth = false
access_key_id = HMAC
secret_access_key = HMAC
endpoint = s3.private.eu-de.cloud-object-storage.appdomain.cloud
```

**Comment by PKehnel** [comment]
@nglange do you guys check issues? ;)

**Comment by nglange** [comment]
@PKehnel Not enough!  

I am pretty certain that you are experiencing the intended behavior.  

- Public endpoints when traffic originates from outside the IBM Cloud.
- Private endpoints when traffic originates from virtual machines or clusters within IBM Cloud.
- Direct endpoints when traffic originates from an isolated network (ie VPC or Direct Link)

**Comment by PKehnel** [comment]
@nglange Thanks for the answer. 

And am I supposed to reach a private COS endpoint when the traffic originates from classic infrastructure?

**Comment by nglange** [comment]
Generally speaking, yes. There might still be some very old Softlayer
infrastructure out there that might not be tied into the 10.x private
network, but if you seem to be having any problems connecting to the
private endpoints from classic infrastructure I’d open a ticket - that
seems weird to me.
