### ISSUE TITLE
Add clarity to cross region endpoints description

### ISSUE THREAD

**Issue by priyanknarvekar** [ibm-cloud-docs/cloud-object-storage#165]
The description of the cross region endpoints appears to be misleading(and incorrect), specially in context of the table below it. 
Users have misinterpreted that , cross region buckets are replicated across "three regions" us, eu and ap.
to the best of my understanding cross region buckets are still within the same geo , but across multiple mzr(s) and single site

it would be good to update to reflect, Buckets that are created at a cross region endpoint distribute data across the mzr's within the geo

https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-endpoints#endpoints-geo
```
Buckets that are created at a cross region endpoint distribute data across three regions. 
Any one of these regions can suffer an outage or even destruction without impacting availability. 
Requests are routed to the nearest Cross Region metropolitan area by using Border Gateway Protocol (BGP) routing. 
In an outage, requests are automatically rerouted to an active region. 
Advanced users who want to write their own failover logic can do so by sending requests to a [tethered endpoint](https://cloud.ibm.com/docs/cloud-object-storage/info?topic=cloud-object-storage-advanced-endpoints) and 
bypassing the BGP routing.
```

**Comment by pdwatters** [comment]
@priyanknarvekar Could you clarify if the Cross Region Endpoints table is incorrect or should not be in that topic?

**Comment by priyanknarvekar** [comment]
@pdwatters this statement , `Buckets that are created at a cross region endpoint distribute data across three regions. Any one of these regions can suffer an outage or even destruction without impacting availability. ...`  **when seen in context of the table ** users would/are interpreting, cross region bucket would spread data across US, EU and AP.  and hence creates confusion, with users asking if their data would cross the geographical boundary. see the screenshot below.

<img width="680" alt="image" src="https://github.com/ibm-cloud-docs/cloud-object-storage/assets/10659853/7be27798-5546-47f8-9953-4b8b4d5a321f">

this interpretation is not correct. Also the column header for the first column "Region" is incorrect, which also add to this confusion. that should be "Geo"

A data in US cross region bucket is distributed only across regions in US, i.e Dallas, WDC and SJC.
A data in EU cross region bucket is distributed only across regions in EU, i.e Amsterdam, FRA and Milan.
Finally data in AP cross region bucket is distributed only across regions in AP, i.e TOK, SYD and OSA.

so either the description needs to be improved, or some other hint needs to be added.

**Comment by pdwatters** [comment]
@priyanknarvekar Please review my updates:
https://test.cloud.ibm.com/docs-draft/cloud-object-storage?topic=cloud-object-storage-endpoints#endpoints-geo

**Comment by priyanknarvekar** [comment]
@pdwatters looks good !
