### ISSUE TITLE
Many broken links in COS docs

### ISSUE THREAD

**Issue by markjmeredith** [ibm-cloud-docs/cloud-object-storage#168]
All the links under https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-gs-dev following the sentence "Developers who want to use Object Storage for persistent storage in their Kubernetes applications can learn more at the following links:" are broken.

**Comment by dpdresse** [comment]
Updated the dead links to work in the topic.  This issue is tracked in https://github.ibm.com/cloud-docs/cloud-object-storage/issues/1266 and has been closed.
