### ISSUE TITLE
white space in cmd

### ISSUE THREAD

**Issue by rhocheck** [ibm-cloud-docs/cloud-object-storage#171]
https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-faq-provision#faq-instance-upgrade

This cmd has white spaces in it and can't be used for c/p

```
ic resource service-instance-update "My Object Storage" --service-plan-id 744bfc56-d12c-4866-88d5- dac9139e0e5d
```

**Comment by dpdresse** [comment]
Fixed, removed the single white-space between - d.
