### ISSUE TITLE
Updates to IBM Cloud Documentation to mount COS using s3fs with RHEL 

### ISSUE THREAD

**Issue by mktse** [ibm-cloud-docs/cloud-object-storage#172]
The IBM Cloud documentation only has references to Debian, Linux, and MacOS, and the available commands for Linux didn't run successfully on my VSI running RHEL 8. For RHEL, you don't have to build the modules for s3fs, you only have to add the EPEL repo to redhead and install s3fs as a package. IBM Cloud Support provided me the following steps for RHEL that may be helpful to update in the documentation: 

For prerequisites for RHEL 7 and above, it was recommended I follow this sequence of commands to successfully install epel and s3fs:

# sudo yum install epel-release
# sudo yum install s3fs-fuse

The epel-release command above didn't work for me, so it was also suggested that I try the below commands (ended up running the dnf install for epel-release, then sudo yum install s3fs-fuse and successfully mounted COS) 

# wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
# rpm -ivh epel-release-latest-8.noarch.rpm

Or the command:
# dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm --nogpgcheck

Other links to reference if above commands don't work: 
https://github.com/s3fs-fuse/s3fs-fuse
https://www.redhat.com/sysadmin/install-epel-linux

**Comment by dpdresse** [comment]
Updated documentation on Mounting a bucket using `s3fs` to include install code and link to https://www.redhat.com/sysadmin/install-epel-linux .
