### ISSUE TITLE
Cloud Assistant - ACS-Storage doc mod/add 

### ISSUE THREAD

**Issue by gaskinner84** [ibm-cloud-docs/cloud-object-storage#173]
https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-getting-started-cloud-object-storage#gs-bucket-policy

"Repeat the above process but in step 3, choose a particular service instance, and enter "bucket" as the Resource Type and the full CRN of an existing bucket as the Resource ID."

Can we kindly provide customer's a link to on how to find the CRN for a COS instance? Maybe in the form of a FAQ question and we can link that FAQ to the word "CRN" in the statement above. 

In summary, reviewing our Cloud Assistant bot questions, we find a lot of customers are asking where to find the CRN for their COS instances. 

The only information I found on CRN in the COS docs is below, which shows an the IBM Cloud shell/cli method of obtaining this. 

https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-ic-cos-cli#ic-iam-authentication

An FAQ that shows both the CLI and UI methods of finding the CRN for COS instances would be a great solution the Cloud Assistant could use for these questions. 

Regards,

Gary S.
ACS-Storage Support Lead
IBM Cloud Support

**Comment by dpdresse** [comment]
Issue has been resolved.
