### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by justin-fleming** [ibm-cloud-docs/cloud-object-storage#176]
This page: https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-fgac-iam-access-conditions&interface=cli references `Scenario 4` three times but when I click the link it takes me to a blank page:

<img width="1719" alt="image" src="https://github.com/ibm-cloud-docs/cloud-object-storage/assets/35156209/a02d0a61-5852-41e9-8487-e0bada46754e">

**Comment by kaloriaibm** [comment]
Issue has been fixed
