### ISSUE TITLE
Missing figure from doc

### ISSUE THREAD

**Issue by ocofaigh** [ibm-cloud-docs/cloud-object-storage#177]
Doc: https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-deleting-multiple-objects-patterns

Looks like the picture is missing here and is instead shown as a code block:
![image](https://github.com/ibm-cloud-docs/cloud-object-storage/assets/29608224/78545b58-8c73-4464-91d1-07b4182b261b)

**Comment by dpdresse** [comment]
Fixed see Issue #177 #1302.
