### ISSUE TITLE
Special characters in tags

### ISSUE THREAD

**Issue by gnietof** [ibm-cloud-docs/cloud-object-storage#178]
According to the documentation, 

**"A Tag key and value may consist of US Alpha Numeric Characters (a-zA-Z0-9), and spaces representable in UTF-8, and the following symbols: !, _, ., *, `, (, ), -, :"**. 

I have received 400 errors when using parenthesis in the tag value. S3 reference in Amazon says that parenthesis are not allowed. So, probably the documentation for IBM Storage is not accurate regarding allowed characters.

**Comment by kaloriaibm** [comment]
According to the IBM Cloud Object Storage topic: https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-object-tagging


A Tag key and value may consist of US Alpha Numeric Characters (a-zA-Z0-9), and spaces representable in UTF-8, and the following symbols: _, ., *, `, -, :
