### ISSUE TITLE
"go get" is deprecated, replaced by "go install"

### ISSUE THREAD

**Issue by marc3977** [ibm-cloud-docs/cloud-object-storage#179]
In this [page](https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-using-go), it says to use the following command to install the SDK:

```
go get github.com/IBM/ibm-cos-sdk-go
```

However, `go get` is deprecated and replaced by `go install`.

**Comment by kaloriaibm** [comment]
The COS SDK is not an executable thus go get is still applicable.   Deprecation of 'go get' for installing executables. https://go.dev/doc/go-get-install-deprecation

**Comment by IBMalok** [comment]
@marc3977  - can you try setting it?  - `go env -w GO111MODULE=auto`
