### ISSUE TITLE
Upload with curl -d/--data vs --data-binary

### ISSUE THREAD

**Issue by SaschaSchwarze0** [ibm-cloud-docs/cloud-object-storage#180]
Under https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-curl#curl-put-object, the sample `curl` command uses `-d`/`--data` which is imo mis-leading here.

The typical use case probably is that I upload a file, but for that to be uploaded without corruption, I must use binary upload (`--data-binary @"<file-path>"`).

**Comment by dpdresse** [comment]
Reviewed with COS developer and discussed that -d is a reasonable example.  As for data integrity, one can use content-md5 or whatever their preferred method is.  The developers feels that trying to add a bunch of unrelated / non-required headers in examples might over-complicate the example.

**Comment by dpdresse** [comment]
No change to curl example at this time.
