### ISSUE TITLE
Set expectations with lite plan enablement process. 

### ISSUE THREAD

**Issue by nikhilshah2** [ibm-cloud-docs/cloud-object-storage#181]
Currently the FAQ directs the customer to submit a ticket for lite plan re-enablement. 

==============================================================================
My COS service is locked. How do I reactivate the COS service?

Exceeding the data limit for the Lite account is one of the reasons why your account is locked or deactived. The [COS support](https://cloud.ibm.com/unifiedsupport/cases/form) team can help to unlock your account.
==============================================================================

Per discussion with offering team, there are a few restrictions that should be made clear to the customer.
* The lite plan account can be activated only once. 
* Upon enablement, customer should reduce the storage to less than 25GB within a week to prevent it from getting disabled again.

**Comment by dpdresse** [comment]
Updated FAQ and created new customer issue to track changes.  Merged changes to production.
