### ISSUE TITLE
"restore a deleted resource" link is not working

### ISSUE THREAD

**Issue by shrvr** [ibm-cloud-docs/cloud-object-storage#185]
### Steps to reproduce
1. Go to https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-provision#delete-instance
2. Click `restore a deleted resource` link.
3. It says page not found.

### Problem
- ❌ It redirects to the https://cloud.ibm.com/docs/docs/account?topic=account-resource-reclamation&interface=api#restore-resource-api

### Expected
- ✅ Should redirect to the correct one:
https://cloud.ibm.com/docs/account?topic=account-resource-reclamation&interface=api#restore-resource-api

Experienced the same issue in the staging environment.

**Comment by dpdresse** [comment]
Found the error is in the path of the MD file.  Fixed and published update.
