### ISSUE TITLE
Update CBR doc to match portal

### ISSUE THREAD

**Issue by stevenolin** [ibm-cloud-docs/cloud-object-storage#186]
Customer is reporting that the documentation on setting up CBR rules is not matching how it is listed in the documentation. They are asking if the documentation can be updated to match how it is shown in the portal.

https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-cos-tutorial-cbr

https://cloud.ibm.com/context-based-restrictions/rules/create

Thanks

**Comment by dpdresse** [comment]
Moved to internal issue.
