### ISSUE TITLE
Ambiguity in describing whether COS IAM action is supported or not

### ISSUE THREAD

**Issue by renusumam** [ibm-cloud-docs/cloud-object-storage#188]
It is not clear from the documentation whether the following IAM actions are supported for COS or are provided just for S3 compatibility:
cloud-object-storage.bucket.get_versioning
cloud-object-storage.object.delete_version
cloud-object-storage.object.get_version

The list given [in the documentation here](https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-iam&interface=ui#iam-actions) does not say anything about these being unsupported, but when checking the list of actions linked to the iam role like Writer for example, these are described as "Unsupported operation - used for S3 API compatibility only."

![Screenshot 2024-07-22 at 9 57 33 AM](https://github.com/user-attachments/assets/efcb268d-a4fc-432c-96b9-b1aacbd5f77c)

**Comment by dpdresse** [comment]
Moved to internal issue.
