### ISSUE TITLE
AttributeError: 's3.Bucket' object has no attribute 'get_bucket_lifecycle_configuration'

### ISSUE THREAD

**Issue by weiliang1216** [ibm-cloud-docs/cloud-object-storage#70]
https://cloud.ibm.com/docs/services/cloud-object-storage?topic=cloud-object-storage-expiry&programming_language=python
According to the doc, I can list the configuration via "response = cos.Bucket('<name-of-bucket>').get_bucket_lifecycle_configuration(
    Bucket='string'
)"
But I found there is no function for "get_bucket_lifecycle_configuration" in the SDK.

**Comment by nglange** [comment]
Hmmm, it might be that you were using a session or resource instead of a client.  I'll update the docs to make that more clear.

https://ibm.github.io/ibm-cos-sdk-python/reference/services/s3.html?highlight=get%20bucket%20lifecycle#S3.Client.get_bucket_lifecycle_configuration
