### ISSUE TITLE
curl examples all require ibm-service-instance-id header

### ISSUE THREAD

**Issue by troyibm** [ibm-cloud-docs/cloud-object-storage#71]
On this doc https://cloud.ibm.com/docs/services/cloud-object-storage/api-reference?topic=cloud-object-storage-curl there are many examples of curl commands and most do not show the use of the `ibm-service-instance-id` header.  This example specifically needs it https://cloud.ibm.com/docs/services/cloud-object-storage/api-reference?topic=cloud-object-storage-curl#curl-list-objects but I think all do.
Spent a loong time trying to figure out what I was doing wrong where the list of buckets was working but the list of files in the bucket wasn't.  :(

**Comment by nglange** [comment]
It is only necessary for operations where the Service Instance being accessed is ambiguous: listing buckets or creating buckets. That is very strange that it caused issues when listing objects - I've verified that it is not required.
