### ISSUE TITLE
Cannot find all information when creating new Service Credentials on Object Storage

### ISSUE THREAD

**Issue by alexdauenhauer** [ibm-cloud-docs/cloud-object-storage#72]
I go here

https://cloud.ibm.com/docs/services/cloud-object-storage?topic=cloud-object-storage-service-credentials

It tells me to go to the side navigation and select Service Credentials. This does not exist. I can create new credentials by clicking the big blue plus sign, but this does not give the `endpoints`, `iam_apikey_description`, `iam_apikey_name`, etc. So how do I retrieve that information?

**Comment by nglange** [comment]
Hey Alex - are you using the older IaaS version of COS?  You should see something like this.
![Screen Shot 2019-09-18 at 10 59 40 AM](https://user-images.githubusercontent.com/439806/65447034-4e32e980-ddfb-11e9-9c82-1b9c00599016.png)

**Comment by alexdauenhauer** [comment]
Yes the issue was that the instructions don't match the classic infrastructure. Finally figured out how to create a cos in the new infrastructure. I still think the docs need an update
