### ISSUE TITLE
Can't Install Aspera SDK

### ISSUE THREAD

**Issue by thevicross** [ibm-cloud-docs/cloud-object-storage#77]
I am trying to install the Aspera SDK on Windows 10 using the following command:
pip install cos-aspera

I get the following error messages:
  ERROR: Could not find a version that satisfies the requirement cos-aspera (from versions: none)
ERROR: No matching distribution found for cos-aspera

**Comment by nglange** [comment]
What version of Python are you using?  The `cos-aspera` package is only available for 2.7 and 3.6.

**Comment by nglange** [comment]
Going to close this due to inactivity, happy to reopen if needed.
