### ISSUE TITLE
Missing 'Expiration rule' section in bucket configuration

### ISSUE THREAD

**Issue by rpiras** [ibm-cloud-docs/cloud-object-storage#79]
In the console I could not find any way for setting the expiration rule for a bucket

**Comment by nglange** [comment]
Did this not work for you?  https://cloud.ibm.com/docs/services/cloud-object-storage?topic=cloud-object-storage-expiry&locale=en-US#expiry-using-console

**Comment by rpiras** [comment]
No, I can't see any widget for this purpose

**Comment by nglange** [comment]
<img width="394" alt="Screen Shot 2019-11-15 at 3 43 28 PM" src="https://user-images.githubusercontent.com/439806/68977848-cfd14300-07be-11ea-947d-5d38ded869c6.png">

Closing this for now as it isn't a documentation problem, but if the problem continues we can open up a console issue.
