### ISSUE TITLE
Getting HTTP Client error using the s3 client 

### ISSUE THREAD

**Issue by ncheaz** [ibm-cloud-docs/cloud-object-storage#82]
Operating system is Ubuntu 16.04
Python version is 3
Installed the AWS CLI using PIP
AWS CLI version is `aws-cli/1.16.309 Python/3.6.9 Linux/4.20.17-042017-generic botocore/1.13.45`

I set the HMAC creds correctly and type the following in my command line:
```
ncheaz@thinkburger:~/Projects/drupal-interact$ aws --endpoint-url 'https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints' s3 ls

An HTTP Client raised and unhandled exception: __init__() got an unexpected keyword argument 'ssl_context'

```

**Comment by cloudpitchford** [comment]
Good morning. What version of `openssl` do you have installed?

**Comment by nglange** [comment]
Closing this for now, but can reopen if @ncheaz needs additional guidance.
