### ISSUE TITLE
bucket permissions page doesn't describe reader & contentReader well

### ISSUE THREAD

**Issue by brittbolen** [ibm-cloud-docs/cloud-object-storage#84]
https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-iam-bucket-permissions

Reader has access to read objects, list objects, and read configuration about the object and bucket among other things.

ContentReader is described as "Download objects" when it can both download and list them.  I find this distinction important and the docs misleading.

**Comment by nglange** [comment]
Fixed, thanks.
