### ISSUE TITLE
Examples of Cache-Control lacking; Content-Type not a common header?

### ISSUE THREAD

**Issue by GreenReaper** [ibm-cloud-docs/cloud-object-storage#85]
[As mentioned here](https://stackoverflow.com/questions/46698696/storing-object-with-control-cache-header-in-object-storage-is-unachievable), it is possible to set Cache-Control with COS; however, although it is now [mentioned as a common header](https://cloud.ibm.com/docs/services/cloud-object-storage?topic=cloud-object-storage-compatibility-common), how to actually achieve set it through the REST API is not set out in an example.

This is quite important for efficient use of COS for file distribution, otherwise you are liable to end up with duplicate requests for the same files (which will hopefully be served with a 304 thanks to ETag, but still).

I uploaded a bunch of files through Aspera Connect before I realized this'd be an issue - though maybe I could have copied them from one bucket to the same bucket, replacing the metadata on them?

Also, is Content-Type a common header? It seems to be, based on the examples, but it isn't called one.

**Comment by cloudpitchford** [comment]
There's apparently some semantic confusion in general about the word "common" and specifically, one HTTP header, "Content-Type" specified in RFC 7231 "Hypertext Transfer Protocol (HTTP/1.1): Semantics and Content" https://tools.ietf.org/html/rfc7231#section-3.1

Mixing storage and HTTP is not uncommon, but they are two different concepts. I hope this helps, but I think what you might be looking for is a static web solution?

**Comment by GreenReaper** [comment]
Well, the way I am using it is static, yes - let me provide more context.

I run a digital art community and we are dipping our toes in the cloud. Object storage has proven useful for storing copies of our site wallpapers - there are several selectable ones, pre-scaled and cropped to various dimensions for efficiency - because they are static, limited in number and have a relatively consistent access pattern thus transfer usage.

As a bonus, IBM Cloud has consistent limits and pricing even in typically-expensive regions such as au-syd. We have an nginx-based private CDN node there, but it has limited disk size and bandwidth. Storing wallpapers in COS means removing some files from that cache and not ever having to fetch them from our main server on the other side of the world for Australian and New Zealand users. Instead, when the wallpaper is requested from the CDN, we redirect the user to an au-syd bucket's [public endpoint](https://cloud.ibm.com/docs/services/cloud-object-storage?topic=cloud-object-storage-endpoints#endpoints), having enabled [public access](https://cloud.ibm.com/docs/services/cloud-object-storage/iam?topic=cloud-object-storage-iam-public-access). (We use Google and Oracle's object stores in Seattle and Saõ Paulo respectively in the same way.)

If we were using this for our main content, we'd still want to use the exact same Cache-Control headers to achieve efficient usage. Content is treated as immutable for this purpose - if the end-user has downloaded it once, there's no need for them to revisit the object; it'd cost them time and us money. If there's a new version we'd change the path.

But none of the IBM REST examples demonstrate how to upload an object such that it will be served with the Cache-Control headers when requested. Clearly it is being done because the CLI tool can do it; I suspect it's a Cache-Control header on the PUT. But this is implied by a mention of it controlling "caching behavior along the request/reply chain" on the common headers page (which does not clearly state that it impacts all future replies to requests for an object). I expected it to be explicit in the sense that it would be listed as an optional header to [PUT object request](https://cloud.ibm.com/docs/services/cloud-object-storage?topic=cloud-object-storage-object-operations#object-operations-put), in the same way that range is listed as an optional header to the [GET object request](https://cloud.ibm.com/docs/services/cloud-object-storage?topic=cloud-object-storage-object-operations#object-operations-get) - and it might be shown as a return value for a GET example as well.

I don't actually need to know this for myself at this time, since we have all our current wallpapers in already and future ones can be added via the CLI tool; but it would be necessary to know before we started to use COS to store all content, because then the sever would have to be uploading objects.

**Comment by cloudpitchford** [comment]
Thanks so much for sharing your solution. And you are not alone in your consideration of NGINX, from what I have heard. Your approach has advantages and more could hear people about this.

And speaking of hearing—are you on Slack? Have you searched for #object-storage and related public channels? The community of developers have a wealth of knowledge and experience, just as you've shared here. I hope they hear from you!
