### ISSUE TITLE
Using C-Sharp to Connect to COS

### ISSUE THREAD

**Issue by kdrayton** [ibm-cloud-docs/cloud-object-storage#86]
I've look all over and can't seem to find any sample code that allows for connecting to IBM's Cloud Object Storage. I attempted to use the libraries available for AWS S3 and though they were easy to use, they seemed to be incompatible with IBM's S3. Is there someone that can provide some insight into connecting to IBM's cloud using C# or .NET code?

**Comment by cloudpitchford** [comment]
There isn't an officially supported .NET SDK, but you can find out more about the available libraries including one that might work for you at:

https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-sdk-about

And to see some—but not all—of the ways to use AWS S3 CLI, check out https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-aws-cli
