### ISSUE TITLE
Broken link to immutable object storage report

### ISSUE THREAD

**Issue by butler54** [ibm-cloud-docs/cloud-object-storage#87]
The compliance report referenced in the [Immutable Object Storage and considerations for various regulations](https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-immutable#immutable-regulation) section [Report link](https://www.ibm.com/downloads/cas/JBDNP0KV) is 404'ing.

**Comment by cloudpitchford** [comment]
In the text, "Review Cohasset Associates Inc.’s *report*…" The link should be: https://www.ibm.com/downloads/cas/MV24AZ13

**Comment by cloudpitchford** [comment]
Also, here's the original announcement (with the same broken link):

https://developer.ibm.com/storage/2018/02/20/ibm-cloud-object-storage-system-reduces-costs-adds-more-regulatory-support/

**Comment by cloudpitchford** [comment]
Please close this issue once reviewed at the Pull Request containing the fix: https://github.ibm.com/cloud-docs/cloud-object-storage/pull/307
