### ISSUE TITLE
The link to "Glossary" leads to a 404

### ISSUE THREAD

**Issue by gokul-uf** [ibm-cloud-docs/cloud-object-storage#88]
Hi,
Clicking on the "Glossary" hyperlink on https://cloud.ibm.com/docs/services/cloud-object-storage?topic=cloud-object-storage-curl  results in a "Page Not Found" error

The exact paragraph was:
"Using curl assumes a certain amount of familiarity with the command line and Object Storage, and have the necessary information from a service credential, the endpoints reference, or the console. If any terms or variables are unfamiliar, they can be found in the _glossary_."

**Comment by nglange** [comment]
Thanks - the object storage glossary was recently combined with [the platform-wide glossary](https://cloud.ibm.com/docs/overview?topic=overview-glossary).  The link has been updated - thanks.
