### ISSUE TITLE
The page "https://cloud.ibm.com/docs/services/cloud-object-storage?topic=cloud-object-storage-velero" is lacking all needed info for Integration

### ISSUE THREAD

**Issue by rashmi-pai** [ibm-cloud-docs/cloud-object-storage#89]
In the page https://cloud.ibm.com/docs/services/cloud-object-storage?topic=cloud-object-storage-velero, section **https://cloud.ibm.com/docs/services/cloud-object-storage?topic=cloud-object-storage-velero#velero-config-storage** seems to be not accurate. 

When Velero tar is extracted, there is no folder like config/common/00-prereqs.yaml or config/ibm. So none of the kubectl commands will work. Is there any other steps needed to get these files in place after extracting the Velero tar ?

Another issue is that the link in "see the instructions at 'run in custom namespace'" seems to be not opening. It gives Page not found.

Kindly update the page.

**Comment by nglange** [comment]
Thanks for the heads up.  I'll take a look at the topic and update it for the latest version of Velero.  It seems like they've moved their docs as part of the split from Heptio - I'll update the links accordingly.

It seems like the newer versions of Velero use `velero install` instead of reading from the yaml file.  While waiting for our topic to be updated, [this topic in the Velero docs](https://velero.io/docs/v1.3.0/contributions/ibm-config/) might be helpful.

**Comment by rashmi-pai** [comment]
Thanks for checking. I could proceed with doc from velero site and other blogs but logged this to get the page corrected as I spend time scratching my head to understand the unrelated stuffs :)

**Comment by Sandeepkallazhi** [comment]
Hello folks. I have found the documentation is not updated. But fortunately I really didn't follow this documentation to get Velero installed on IKS with COS as object store. The issue I have is weird. 
This is my Velero Install command
velero install \
    --provider aws \
    --bucket cloud-object-storage-43-cos-standard-fhd  \
    --secret-file ./credentials-velero \
    --use-volume-snapshots=false \
    --backup-location-config region=us-east,s3ForcePathStyle="true",s3Url=s3.us-east.cloud-object-storage.appdomain.cloud
    --plugins velero/velero-plugin-for-aws:v1.0.0
The namespace, deployment and the pod gets created, but the pods dies soon enough, goes from Running, to error and CrashLoopbackoff. Its gives the following events in the pod description. Wondering if someone has come this far and had found a fix or have been able to get beyond, please assist. Thanks

Events:
  Type     Reason   Age                     From                    Message
  ----     ------   ----                    ----                    -------
  Normal   Pulled   28m (x258 over 22h)     kubelet, 10.76.165.174  Container image "velero/velero:v1.3.0" already present on machine
  Warning  BackOff  3m38s (x6040 over 22h)  kubelet, 10.76.165.174  Back-off restarting failed container

**Comment by nglange** [comment]
@Sandeepkallazhi Did you try adding the `--wait` flag?  I had replied to you in another thread, but there are a lot of different issue threads for this problem so it might have gotten missed.  I'm going to close this issue as this is being handled directly by customer support, but feel free to comment here and I can reply directly.
