### ISSUE TITLE
How to resolve "No resource group" error during creation of COS.

### ISSUE THREAD

**Issue by kiranshashiny** [ibm-cloud-docs/cloud-object-storage#93]
I am getting this error when I followed the steps.

ibmcloud login was successful, but the next step failed !

I'm on Windows 10 and using gitbash.
The URL I am following is 

https://cloud.ibm.com/docs/services/cloud-object-storage/basics?topic=cloud-object-storage-gs-dev
![image](https://user-images.githubusercontent.com/14288989/79638942-0cf29480-81a6-11ea-8b52-e301a7c2c791.png)

$ ibmcloud resource service-instance-create stocksinstance cloud-object-storage Standard global
FAILED
No resource group targeted. Use 'C:\Program Files\IBM\Cloud\bin\ibmcloud.exe target -g RESOURCE_GROUP' to target a resource group.

**Comment by nglange** [comment]
That’s odd - I had thought a default resource group would automatically be selected. I’ll take a look.

**Comment by nglange** [comment]
What version of the CLI are you using?

**Comment by nglange** [comment]
Seems like you need to set your resource group explicitly. I'll update the docs, but here's the gist.

First, you can see what resource groups you have available: `ic resource groups`

Then set the resource group you want the instance to live in: `ic target -g <group>`

Then you should be able to run the command as expected.

**Comment by nglange** [comment]
This has been added, closing as there's been no response.

**Comment by kiranshashiny** [comment]
Thanks I got it going. 

Using this instead.


https://github.com/IBM/cos-sample-scripts-js/blob/master/src/standardBucketOperations.js

Appreciate your responses above.

Please close. Sorry about not reverting earlier.
