### ISSUE TITLE
Getting Started with IAM in COS

### ISSUE THREAD

**Issue by Slagendish** [ibm-cloud-docs/cloud-object-storage#95]
After reading the "Getting Started with IAM" in Cloud Object Storage section, it's not clear that the roles can be defined for an higher level in term of granularity (Like only on one Bucket) by going in the IAM section.

When I create an HMAC credential from the COS panel, my Service ID get access rigths on the complete COS instance. It was not clear that I had to go in the IAM section and update the role for this service to restrict the access on the Bucket level. 
A small note on it and a link to the 'Bucket Permission' section in COS should be enough to make it clear.

**Comment by nglange** [comment]
Thanks for the helpful feedback. Unfortunately the publishing process doesn’t allow for direct PRs against this repo, but I’ll ping you in this comment when the updated version is available.

**Comment by cloudpitchford** [comment]
I'm going to close this ticket as inactive for a month, but please re-open or start a new dialogue if needed. Thanks!
