### ISSUE TITLE
in Java largeObjectUpload,  COS_BUCKET_LOCATION is undefined

### ISSUE THREAD

**Issue by keshlam** [ibm-cloud-docs/cloud-object-storage#97]
It appears to be intended to be the Storage Class Location (eg "us-south"), but if so the "BUCKET" is a bit misleading..

**Comment by cloudpitchford** [comment]
Assigned, and will review.

@nglange please feel free to re-assign based on your investigation.

**Comment by cloudpitchford** [comment]
The changes made to the Java sample are in production. Please review and close this issue as appropriate. Thanks!
